<?php
// Job Lister Free Version - https://www.netartmedia.net/job-lister
// A software product of NetArt Media, All Rights Reserved
// The following source codes are obfuscated / made difficult to edit. 
// When upgrading to Job Lister PRO, you get the full non-obfuscated source codes 
// and also extra features - please find details on:
// https://www.netartmedia.net/job-lister#pro
// Find out more PHP scripts and ready-made website systems on:
// https://www.netartmedia.net/products
?><div class="card" style="padding-left:20px;padding-right:20px"> <div class="content"> <h3> Upgrade now to the PRO version of Job Lister </h3> <br/> <div class="row"> <div class="col-md-6"> <h4>Get access to the script source codes</h4> You or developers working for you can edit the source codes on your website to customize the default functionality or add new custom features you may need. In the free version of Job Lister, the source codes are obfuscated and made to be difficult to edit or customize. </div> <div class="col-md-6"> <img src="images/editable-source-codes.jpg" class="img-responsive"/> </div> </div> <br/><br/> <div class="row"> <div class="col-md-6"> <img src="images/job-apply-form.jpg" class="img-responsive"/> </div> <div class="col-md-6"> <h4>Job Application form</h4> This functionality allows the users to directly apply for the job offers on your site by submitting their resume and entering their name, address, phone and email address. </div> </div> <br/><br/> <div class="row"> <div class="col-md-6"> <h4>No Powered By link</h4> The Pro version comes with no powered by link and you are not required to keep any links back to us or references. With the free version, you are required to keep the default powered by link at the bottom of the site. </div> <div class="col-md-6"> <img src="images/no-powered-by.jpg" class="img-responsive"/> </div> </div> <br/><br/> <div class="row"> <div class="col-md-6"> <img src="images/seo-functionality.jpg" class="img-responsive"/> </div> <div class="col-md-6"> <h4>SEO URLs functionality</h4> The SEO URLs functionality that can be turned on from the administration panel and makes the job listing and other front-end pages to look like static html pages and having keywords in the URLs (for example https://www.domain.com/job-title-1.html instead of https://www.domain.com/index.php?page=job&id=1). This allows better indexing in search engines like Google and can improve the position in the Google search results. </div> </div> <br/><br/> <div class="row"> <div class="col-md-6"> <h4>Free technical support and exclusive discounts for our other products</h4> We offer a free technical support and also a free installation service for the Pro version. If you have any questions or experience a technical problem, you can contact our support team and we'll do our best to help. You also get exclusive discounts and special offers for our other PHP scripts and ready-made website systems. </div> <div class="col-md-6"> <img src="images/free-technical-support.jpg" class="img-responsive"/> </div> </div> <br/><br/> <br/> <a href="https://www.netartmedia.net/order#job-lister" class="btn btn-primary" target="_blank"> ORDER NOW THE PRO VERSION - $69<sup>.00</sup> </a> <br/> <br/> <br/> </div> </div> 