<?php
// Job Lister Free Version - https://www.netartmedia.net/job-lister
// A software product of NetArt Media, All Rights Reserved
// The following source codes are obfuscated / made difficult to edit. 
// When upgrading to Job Lister PRO, you get the full non-obfuscated source codes 
// and also extra features - please find details on:
// https://www.netartmedia.net/job-lister#pro
// Find out more PHP scripts and ready-made website systems on:
// https://www.netartmedia.net/products
?><?php define("IN_SCRIPT","1"); error_reporting(0); session_start(); include("../include/sm.php"); $website = new SiteManager(); $website->hdsy(); ?> <!DOCTYPE html> <html lang="en"> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <meta charset="utf-8"> <title>Job Lister Administration Panel</title> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta name="description" content=""> <meta name="author" content=""> <script src="js/jquery-1.10.2.js" type="text/javascript"></script> <link rel="stylesheet" type="text/css" href="css/login.css"> <script type="text/javascript" src="js/login.js"></script> </head> <body> <div class="page-header"> <h1><a href="https://www.netartmedia.net/job-lister" style="color:#636363;text-decoration:none">Job Lister</a></h1> <h3><?php echo $website->fjod["login_to_continue"];?></h3> <br/> </div> <form id="main" style="margin-top:0px" action="login_action.php" method="post"> <div class="group"> <input name="username" required type="text"><span class="highlight"></span><span class="bar"></span> <label><?php echo $website->fjod["username"];?></label> </div> <div class="group"> <input name="password" required type="password"><span class="highlight"></span><span class="bar"></span> <label><?php echo $website->fjod["password"];?></label> </div> <input type="submit" class="button buttonBlue" value="<?php echo $website->fjod["login"];?>"/> </form> <footer> <p><!--Find more free scripts and complete website systems on our <a href="https://www.netartmedia.net/scripts.html" class="underline-link" target="_blank">PHP Scripts</a> page.--></p> </footer> </body> </html>