<?php
// Job Lister Free Version - https://www.netartmedia.net/job-lister
// A software product of NetArt Media, All Rights Reserved
// The following source codes are obfuscated / made difficult to edit. 
// When upgrading to Job Lister PRO, you get the full non-obfuscated source codes 
// and also extra features - please find details on:
// https://www.netartmedia.net/job-lister#pro
// Find out more PHP scripts and ready-made website systems on:
// https://www.netartmedia.net/products
?><?php if(!isset($_REQUEST["page"]) && !isset($_REQUEST["mod"])) { ?> <header class="top-header" style="background-image: url('uploaded_images/<?php echo $this->information->intro_background;?>.jpg')"> <div class="overlay"></div> <div class="container"> <div class="row"> <div class="col-lg-12 mx-auto"> <div class="site-heading"> <h1 style="margin-bottom:15px"><?php echo $this->information->intro_title;?></h1> <div class="col-md-10 mx-auto"> <form action="index.php" method="post"> <input type="hidden" name="page" value="posts"/> <div class="form-row"> <div class="col-12 col-md-5"> <input type="text" name="keyword" class="form-control form-control-lg" placeholder="<?php echo $this->fjod["keyword"];?> ..."> </div> <div class="col-12 col-md-4"> <select name="job_category" class="form-control form-control-lg"> <option value=""><?php echo $this->fjod["job_category"];?></option> <?php $uwegb = file_get_contents('include/categories.php'); $cythngr = explode("\n", trim($uwegb)); foreach($cythngr as $nkpzrv) { list($key,$ysouue)=explode(". ",$nkpzrv); $zprvsw = $this->zprvsw($key, $ysouue); echo '<option value="'.$key.'">'.$ysouue.'</option>'; } ?> </select> </div> <div class="col-12 col-md-3"> <button type="submit" class="btn btn-primary btn-lg" style="width:100%;min-height:48px"><?php echo $this->fjod["search"];?></button> </div> </div> </form> </div> </div> </div> </div> </div> </header> <?php } ?>